#!/usr/bin/env python3
"""Add a neutral, June-2021-anchored 'companyBlurb' to each of the 50 stocks
in data/snapshot-2021.json. No good/bad framing, no forward-looking info."""
import json
from collections import OrderedDict

BLURBS={
"HDFCBANK":"HDFC Bank is one of India's largest private-sector banks by assets, offering retail and wholesale banking, loans, cards and payment services nationwide. It operates in the Banking sector, with a franchise built on a large low-cost deposit base and an extensive branch and digital network. As of June 2021 it was among the most valuable listed banks in India.",
"KOTAKBANK":"Kotak Mahindra Bank is a private-sector bank that anchors a broader financial-services group spanning lending, broking, asset management and insurance. It belongs to the Banking sector and is known for a conservative, high-margin approach and a strong low-cost (CASA) deposit franchise. As of June 2021 it ranked among India's larger private banks by market value.",
"AXISBANK":"Axis Bank is one of India's large private-sector banks, providing retail, corporate and SME banking alongside cards, loans and treasury services through a nationwide branch and digital network. It operates in the Banking sector. As of June 2021 it was the third-largest private-sector bank in India by assets.",
"TATAMOTORS":"Tata Motors is an Indian automaker that designs and sells passenger and commercial vehicles and, through its Jaguar Land Rover subsidiary, luxury cars worldwide. It operates in the Automobile sector as the flagship auto company of the Tata group. As of June 2021 it was one of India's largest vehicle makers by revenue, with earnings heavily influenced by its global JLR business.",
"BAJAJFINSV":"Bajaj Finserv is the financial-services holding company of the Bajaj group, with interests in consumer and SME lending and in life and general insurance joint ventures. It sits in the NBFC / Financial Services space, holding the group's stake in Bajaj Finance along with its insurance businesses. As of June 2021 it was one of India's most prominent diversified financial-services groups.",
"BAJFINANCE":"Bajaj Finance is one of India's largest non-bank lenders (NBFC), focused on consumer-durable, personal, SME and mortgage financing with a very large customer base. It operates in the NBFC / Financial Services sector and is known for a diversified retail loan book and an extensive point-of-sale financing network. As of June 2021 it was among the largest NBFCs in India by assets.",
"SUNDARMFIN":"Sundaram Finance is a non-bank financial company (NBFC) in the TVS group, specialising in financing commercial vehicles, cars and other assets. It operates in the NBFC / Financial Services sector with a long-established presence in south India. As of June 2021 it was regarded as one of the country's older and more conservatively run vehicle financiers.",
"AAVAS":"Aavas Financiers is a housing-finance company focused on affordable home loans for lower-income and self-employed borrowers in semi-urban and rural India. It operates within the NBFC / Financial Services (housing finance) space. As of June 2021 it was among the listed affordable-housing-finance specialists serving under-banked customers.",
"CYIENT":"Cyient is an Indian technology company providing engineering and digital services, including product design, geospatial and IT solutions for sectors such as aerospace, communications and utilities. It operates in the IT Services sector with a focus on engineering R&D (ER&D). As of June 2021 it was a mid-sized Indian IT and engineering-services provider.",
"MPHASIS":"Mphasis is an IT-services company offering application development, cloud and digital-transformation services, with a strong orientation toward banking and financial-services clients. It operates in the IT Services sector. As of June 2021 it was a mid-cap Indian IT firm majority-owned by a private-equity-led group.",
"HCLTECH":"HCL Technologies is one of India's largest IT-services companies, combining software services with a sizeable infrastructure-management business, engineering/R&D services and a software-products portfolio. It operates in the IT Services sector. As of June 2021 it was among the top tier of Indian IT exporters.",
"TECHM":"Tech Mahindra is a large IT-services company within the Mahindra group, with particular strength in telecom/communications alongside enterprise digital and IT services. It operates in the IT Services sector. As of June 2021 it was one of India's larger IT exporters with a notable network-services focus.",
"ZENSARTECH":"Zensar Technologies is an IT-services company in the RPG group, providing digital, application and infrastructure services to global clients. It operates in the IT Services sector. As of June 2021 it was a mid-sized Indian IT firm focused on digital and experience services.",
"COFORGE":"Coforge, formerly NIIT Technologies, is an IT-services company specialising in digital solutions for industries such as banking, insurance and travel. It operates in the IT Services sector. As of June 2021 it had recently rebranded from NIIT Technologies and was a mid-cap Indian IT provider.",
"INFY":"Infosys is one of India's largest IT-services companies, offering consulting, software development, cloud and digital-transformation services to global enterprises on a largely export-driven model. It operates in the IT Services sector. As of June 2021 it was India's second-largest IT-services firm by revenue.",
"WIPRO":"Wipro is a large Indian IT-services company providing consulting, application, cloud and engineering services globally, alongside some smaller non-IT businesses. It operates in the IT Services sector. As of June 2021 it was among the top Indian IT exporters by revenue.",
"BIOCON":"Biocon is a biopharmaceutical company focused on biosimilars, insulins and active pharmaceutical ingredients, with a research-services arm. It operates in the Pharma / Biotech sector and is one of India's leading biotechnology firms. As of June 2021 it was notable for a biosimilars pipeline developed partly through global partnerships.",
"DRREDDY":"Dr. Reddy's Laboratories is a global generics-led pharmaceutical company with significant US exposure and an active API (active pharmaceutical ingredients) business. It operates in the Pharma / Biotech sector. As of June 2021 it was one of India's largest drugmakers by revenue.",
"CIPLA":"Cipla is a major Indian pharmaceutical company known particularly for respiratory therapies and a broad branded-generics portfolio, with US and emerging-market businesses. It operates in the Pharma / Biotech sector. As of June 2021 it was among India's leading drugmakers.",
"DIVISLAB":"Divi's Laboratories is one of the world's largest manufacturers of active pharmaceutical ingredients (APIs) and custom synthesis for global innovator drug companies. It operates in the Pharma / Biotech sector. As of June 2021 it was a high-margin, capacity-led API specialist.",
"GODREJCP":"Godrej Consumer Products is an FMCG company making home and personal-care products such as soaps, hair colour and household insecticides, with operations across India, Africa and Indonesia. It operates in the FMCG sector. As of June 2021 it was a leading household and personal-care player in several emerging markets.",
"COLPAL":"Colgate-Palmolive (India) is an FMCG company that leads the Indian oral-care market with toothpaste, toothbrushes and related products, alongside some personal-care lines. It operates in the FMCG sector as the local arm of the global Colgate-Palmolive group. As of June 2021 it was the market leader in toothpaste in India.",
"JYOTHYLAB":"Jyothy Labs is an FMCG company with household and personal-care brands spanning fabric care (Ujala), dishwash (Exo, Pril), household insecticides (Maxo) and detergents (Henko). It operates in the FMCG sector. As of June 2021 it was a mid-sized Indian household-products company.",
"BRITANNIA":"Britannia Industries is an FMCG company and one of India's leading makers of biscuits, with a growing presence in bakery and dairy products. It operates in the FMCG sector behind well-known brands and a wide distribution network. As of June 2021 it was among the country's largest packaged-foods companies.",
"TATACONSUM":"Tata Consumer Products is an FMCG company in the Tata group selling branded beverages and foods, including tea, coffee, packaged salt and staples (brands such as Tata Tea, Tetley and Tata Salt). It operates in the FMCG sector. As of June 2021 it had recently been reorganised to bring the group's consumer businesses under one entity.",
"MARICO":"Marico is an FMCG company built on hair oils (Parachute), edible oils (Saffola) and a growing foods and premium personal-care portfolio. It operates in the FMCG sector across India and select international markets. As of June 2021 it was a leading player in coconut and value-added hair oils.",
"NESTLEIND":"Nestlé India is the Indian arm of the global Nestlé group, selling packaged foods and beverages including noodles (Maggi), instant coffee, dairy, chocolates and infant nutrition. It operates in the FMCG sector behind strong brands. As of June 2021 it followed a January-December financial year and was a leading branded-foods company in India.",
"ITC":"ITC is a diversified company whose largest profit contributor is its cigarettes business, alongside FMCG foods and personal care, hotels, paperboards and packaging, and agri-business. Given its consumer focus it is grouped here in the FMCG sector. As of June 2021 it was one of India's largest cigarette makers and a major branded-foods player.",
"VBL":"Varun Beverages is one of the largest franchisee bottlers of PepsiCo products outside the United States, producing and distributing carbonated soft drinks, juices and packaged water. It operates in the Beverages sector across India and parts of Africa. As of June 2021 it was PepsiCo's key bottling partner across much of India.",
"HAVELLS":"Havells India is an electrical and consumer-durables company making wires and cables, switchgear, lighting, fans and home appliances, including the Lloyd brand. It operates in the Consumer Durables / electricals sector. As of June 2021 it was a leading Indian electrical-goods maker with a wide dealer network.",
"VOLTAS":"Voltas, a Tata group company, is a leading maker of air conditioners and cooling products that also runs an engineering and electro-mechanical projects business. It operates in the Consumer Durables sector. As of June 2021 it was the market leader in room air conditioners in India.",
"ASTRAL":"Astral is a building-materials company best known for CPVC and PVC plumbing and piping systems, alongside an adhesives business. It operates in the Industrials / Building Materials sector. As of June 2021 it was a prominent branded pipes-and-adhesives maker in India.",
"KAJARIACER":"Kajaria Ceramics is India's largest manufacturer of ceramic and vitrified tiles, with additional sanitaryware and faucet lines. It operates in the Industrials / Building Materials sector. As of June 2021 it was the country's leading tile maker by capacity.",
"AMBUJACEM":"Ambuja Cements is one of India's major cement producers, manufacturing and selling cement and related building materials. It operates in the Industrials / Building Materials sector and was, as of June 2021, part of the global Holcim group, following a January-December financial year.",
"CERA":"Cera Sanitaryware is a building-products company making sanitaryware, faucets, tiles and bathroom fittings. It operates in the Industrials / Building Materials sector. As of June 2021 it was among India's well-known bathroom-and-tiles brands.",
"SUPREMEIND":"Supreme Industries is one of India's largest plastic-products companies, making piping systems, packaging films, moulded furniture and industrial and consumer plastics. It operates in the Industrials / Building Materials (plastics) sector. As of June 2021 it was a diversified plastics maker with a broad product range.",
"GRINDWELL":"Grindwell Norton, part of the Saint-Gobain group, manufactures abrasives and ceramics/silicon-carbide products used across industry. It operates in the Industrials / Building Materials sector as a supplier of industrial consumables. As of June 2021 it was a long-established maker of abrasives in India.",
"RELIANCE":"Reliance Industries is India's largest company by market value, with core operations in oil refining and petrochemicals alongside fast-growing telecom (Jio) and retail businesses. It is grouped in the Energy / Oil & Gas sector, reflecting its refining-and-chemicals base. As of June 2021 it was expanding its consumer-facing digital and retail segments.",
"BPCL":"Bharat Petroleum (BPCL) is a state-owned oil company that refines crude oil and markets petrol, diesel and other fuels through a large retail network. It operates in the Energy / Oil & Gas sector as one of India's major oil-marketing companies. As of June 2021 the government had announced plans for its strategic disinvestment.",
"ADANIGREEN":"Adani Green Energy is one of India's largest renewable-power producers, developing and operating solar and wind generation projects. It operates in the Power / Utilities sector as part of the Adani group. As of June 2021 it was among the country's biggest listed renewable-energy companies by capacity.",
"RPOWER":"Reliance Power, part of the Reliance Group, develops and operates power-generation projects spanning thermal and renewable sources, including the Sasan ultra-mega power plant. It operates in the Power / Utilities sector as an independent power producer. As of June 2021 it ran a portfolio of generation assets.",
"GUJGASLTD":"Gujarat Gas is India's largest city gas distribution company by volume, supplying piped natural gas (PNG) to homes and industry and compressed natural gas (CNG) for vehicles, mainly in Gujarat. It operates in the Gas Distribution sector. As of June 2021 it had the country's largest CGD network by sales volume.",
"IGL":"Indraprastha Gas (IGL) is a city gas distribution company supplying CNG for vehicles and piped natural gas to homes and businesses, primarily in the Delhi-NCR region. It operates in the Gas Distribution sector. As of June 2021 it was the dominant CNG/PNG supplier in the national capital region.",
"AARTIIND":"Aarti Industries is a specialty-chemicals company producing benzene-based and other chemical intermediates used in pharmaceuticals, agrochemicals, dyes and polymers. It operates in the Specialty Chemicals sector, serving both domestic and export markets. As of June 2021 it was a leading Indian maker of certain benzene-derivative chemistries.",
"GARFIBRES":"Garware Technical Fibres makes technical textiles and synthetic cordage - ropes, nets and twines for fishing, aquaculture, sports, agriculture and industrial uses. It operates in the Textiles (technical textiles) sector. As of June 2021 it was a specialised maker of high-performance synthetic netting and cordage with significant exports.",
"RAJESHEXPO":"Rajesh Exports is a vertically integrated gold company spanning refining, jewellery manufacturing and retail (Shubh Jewellers). It operates in the Jewellery / gold sector and is among the world's largest processors of gold by volume. As of June 2021 it ran operations from refining through to branded retail.",
"RELAXO":"Relaxo Footwears is one of India's largest footwear makers, producing affordable and mid-range slippers, sandals and shoes under brands such as Relaxo, Sparx, Flite and Bahamas. It operates in the Footwear sector. As of June 2021 it was a leading manufacturer in the value footwear segment by volume.",
"ZEEL":"Zee Entertainment Enterprises is a media and entertainment company operating television channels across languages, a content and film business, and the ZEE5 streaming platform. It operates in the Media sector. As of June 2021 it was one of India's largest listed broadcasters by viewership.",
"JPASSOCIAT":"Jaiprakash Associates is a diversified infrastructure conglomerate with operations in engineering and construction, cement manufacturing and real estate, and a track record of large projects such as expressways and hydropower plants. It operates in the Infrastructure / Cement sector. As of June 2021 it was one of India's diversified infrastructure groups.",
"PAYTM":"Paytm, operated by One97 Communications, is a digital-payments and financial-services platform offering a mobile wallet, UPI payments, merchant services and related consumer financial products. It operates in the Fintech sector. As of June 2021 it was among India's most widely used digital-payments brands by user base.",
}

snap=json.load(open("data/snapshot-2021.json"))
missing=[t for t in snap if t not in BLURBS]
assert not missing, f"missing blurbs: {missing}"
extra=[t for t in BLURBS if t not in snap]
assert not extra, f"extra blurbs: {extra}"

out=OrderedDict()
for t,v in snap.items():
    nd=OrderedDict()
    nd["name"]=v["name"]
    nd["companyBlurb"]=BLURBS[t]
    for k,val in v.items():
        if k!="name": nd[k]=val
    out[t]=nd

json.dump(out,open("data/snapshot-2021.json","w"),indent=1,ensure_ascii=False)
print(f"Injected companyBlurb for {len(out)} stocks.")
# length sanity
for t,v in out.items():
    n=v["companyBlurb"].count(".")
    if not (2<=len(v["companyBlurb"])<=600): print("LEN?",t,len(v["companyBlurb"]))
print("All blurbs present and sized OK.")
